{"uuid": "05bfd866-a1c6-41f9-9bad-d5eee881ceb8", "children": ["d7c49fee-e9f1-4a65-9976-b6421bd092a0", "ae2dc5e5-fcc2-40ca-8051-adf1aa8f5e78", "c7bf7fb9-b4e9-4628-9a57-18cec90a444a", "afedd712-2408-4c33-80f2-ce76ce4fc55f", "b8f1895a-7a78-4831-9711-df4eb90a94e7", "eff466be-e677-4ed1-b475-4cf491e7e8e4", "aefec4a5-0953-41ef-b1c5-1c81c8cd5492", "d4383cc1-3506-4866-a3c6-0dd6c0661958", "fa03aab7-b587-4f27-9076-3e1ee4a16e2f", "39f88cd4-d7ca-4ce2-ac5d-f3d213b7822f", "f990e606-5e9e-4456-958c-7394359ad73d", "bf74d9db-0451-4def-95f8-862ea66828a4"], "befores": [{"name": "_Class__pytest_setup_class", "status": "broken", "statusDetails": {"message": "KeyError: 'data'\n", "trace": "  File \"C:\\Users\\q\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\q\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\q\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\q\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\_pytest\\python.py\", line 703, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"C:\\Users\\q\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\_pytest\\python.py\", line 634, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\autoTest\\testcases\\cdn\\ctyun_console\\test_ctyun_order.py\", line 31, in setup_class\n    self.domain_list = self.orderData.order_domainlist()\n  File \"D:\\autoTest\\bin\\createOrder.py\", line 145, in order_domainlist\n    all_domain = [domain.get(\"name\") for domain in content[\"data\"][\"list\"] if domain[\"enable\"] == \"true\"]\n"}, "start": 1606461312144, "stop": 1606461312193}], "start": 1606461312144, "stop": 1606461312368}