{"name": "test_CDN_246180", "status": "failed", "statusDetails": {"message": "AssertionError: assert '服务调用成功' in '{\"duration\":\"2641485\",\"reason\":\"当前会话未登录或已超时，您需要重新登录\",\"code\":\"core.e1019\",\"data\":{\"name\":\"Auto_Cert_Uhxa\",\"certs\":\"---...A PRIVATE KEY-----\\\\n\",\"email\":\"286036139@qq.com\",\"workspaceId\":\"10039265\"},\"serial\":\"d98245f6\",\"host\":\"*.*.*.1:9810\"}'\n +  where '{\"duration\":\"2641485\",\"reason\":\"当前会话未登录或已超时，您需要重新登录\",\"code\":\"core.e1019\",\"data\":{\"name\":\"Auto_Cert_Uhxa\",\"certs\":\"---...A PRIVATE KEY-----\\\\n\",\"email\":\"286036139@qq.com\",\"workspaceId\":\"10039265\"},\"serial\":\"d98245f6\",\"host\":\"*.*.*.1:9810\"}' = <Response [200]>.text", "trace": "self = <ctyun_console.test_ctyun_cert.Test_Ctyun_cert object at 0x0000024239F3CF98>\n\n    @allure.severity('blocker')\n    @allure.story('证书创建成功')\n    def test_CDN_246180(self):\n        console_host = self.base_info['ctyunHost']\n        workspace_id = self.base_info['ctyun_workspaceid']\n        email = self.base_info['email']\n        createCert_url = console_host + self.cert_info['createCert']\n        select_cert_url = console_host + self.cert_info['viewCert']\n        cert_name = 'Auto_Cert_' + random_string(4)\n        createCert_data = {\n            \"data\": {\"workspaceId\": workspace_id, \"name\": cert_name, \"certs\": public_key_365, \"key\": private_key_365,\n                     \"email\": email}}\n        cert_response = self.session.post(url=createCert_url, data=json.dumps(createCert_data), headers=headers_json,\n                                          verify=False, timeout=10)\n        print(\"-------------------创建证书-------------------\")\n        print('请求url: ' + str(createCert_url))\n        print(\"请求data: \" + str(createCert_data))\n        print(\"返回： \" + str(cert_response.text))\n        print(\"重点验证：\" + cert_name + \"  expect： 返回里面有证书名\")\n        assert cert_name in cert_response.text\n>       assert '服务调用成功' in cert_response.text\nE       assert '服务调用成功' in '{\"duration\":\"2641485\",\"reason\":\"当前会话未登录或已超时，您需要重新登录\",\"code\":\"core.e1019\",\"data\":{\"name\":\"Auto_Cert_Uhxa\",\"certs\":\"---...A PRIVATE KEY-----\\\\n\",\"email\":\"286036139@qq.com\",\"workspaceId\":\"10039265\"},\"serial\":\"d98245f6\",\"host\":\"*.*.*.1:9810\"}'\nE        +  where '{\"duration\":\"2641485\",\"reason\":\"当前会话未登录或已超时，您需要重新登录\",\"code\":\"core.e1019\",\"data\":{\"name\":\"Auto_Cert_Uhxa\",\"certs\":\"---...A PRIVATE KEY-----\\\\n\",\"email\":\"286036139@qq.com\",\"workspaceId\":\"10039265\"},\"serial\":\"d98245f6\",\"host\":\"*.*.*.1:9810\"}' = <Response [200]>.text\n\ntestcases\\cdn\\ctyun_console\\test_ctyun_cert.py:67: AssertionError"}, "start": 1606461307284, "stop": 1606461307745, "uuid": "625be905-6e32-45b2-959a-0d8ce653fee1", "historyId": "e1a2c22feba99e8c32d22300b8ab5199", "testCaseId": "11ec356725d66ded5005f5ad0d7019a9", "fullName": "testcases.cdn.ctyun_console.test_ctyun_cert.Test_Ctyun_cert#test_CDN_246180", "labels": [{"name": "story", "value": "证书创建成功"}, {"name": "feature", "value": "CTYUN 客户控制台-证书模块"}, {"name": "severity", "value": "blocker"}, {"name": "parentSuite", "value": "testcases.cdn.ctyun_console"}, {"name": "suite", "value": "test_ctyun_cert"}, {"name": "subSuite", "value": "Test_Ctyun_cert"}, {"name": "host", "value": "LAPTOP-0QCFU979"}, {"name": "thread", "value": "8704-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.cdn.ctyun_console.test_ctyun_cert"}]}